# Generated by Django 2.1.3 on 2018-11-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='user', db_index=True, help_text='请输入用户名', max_length=12, null=True, verbose_name='用户名')),
                ('user_type', models.IntegerField(choices=[(0, '普通用户'), (1, '超级用户'), (2, 'VIP用户')])),
            ],
        ),
    ]
